name: ts-sdk Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Clean install
        run: |
          npm install
          npm install @rollup/rollup-linux-x64-gnu

      - name: Build
        run: npm run build