name: ts-sdk Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Install peer dependencies (CI only)
        run: |
          echo "Installing peer dependencies for type checking..."
          bun add @buildonspark/issuer-sdk@latest @buildonspark/spark-sdk@latest --exact

      - name: Build
        run: bun run build