name: Check Yarn Lock

on:
  push:
  workflow_dispatch:

jobs:
  check:
    name: Check yarn.lock
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install --frozen-lockfile --check-files

      - name: Check yarn.lock integrity
        run: yarn check --integrity --verify-tree
