name: ts-sdk Lint

on:
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - "tests/**"
      - "index.ts"
      - "biome.json"
      - ".github/workflows/lint.yml"
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for --changed flag

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest

      - name: Run Biome Check
        run: |
          biome ci \
            --files-ignore-unknown=true \
            --formatter-enabled=true \
            --linter-enabled=true \
            --javascript-formatter-enabled=true \
            --javascript-linter-enabled=true \
            --error-on-warnings \
            --verbose \
            --diagnostic-level=warn \
            "src/**/*.ts" "tests/**/*.{ts,js,mjs,cjs}" "index.ts" 